### ISSUE TITLE
[TASK] Asyncify and productionize the networking

### ISSUE THREAD

**Issue by drewstone** [webb-tools/zk-SaaS#15]
# Overview
Our stack relies on async networking so we ought to convert these distributed operations into async rust. All `dist-primitives` would be candidates for conversion.

### First-order tasks
Make the networking usable and safe to operate in a production environment
- [x] Async each distributed function
- [x] Use cfg iter on iterators and parallelize as much as possible for multi-threaded performance
- [x] Work over any Arkworks field and hash digest
- [x] Streaming-friendly interfaces/functions. Large messages (millions of group elements) should be able to be streamed to receivers.  
- [x] Secure the transport layer (mTLS)

### Second-order tasks
Integrate the `ProdNet` into a `zkGadget`
- [x] Create a JobManager repository that can be used by both the DKG gadget and this repo
- [ ] Design protocol for handling job requests from a source (later, this source will be the blockchain)
- [ ] Combine both the job protocol and the `ProdNet` implementation to create a `zkGadget`

### Misc tasks
- [ ] Benchmark and wrap long-running computations (>10ms) inside `tokio::task::spawn_blocking` to improve performance

**Comment by drewstone** [comment]
@tbraun96 I updated this tasks with the new requirements

**Comment by tbraun96** [comment]
@drewstone I updated this list with some ideas on how to proceed forward. They will obviously need a bit more speccing, but, I think we can talk during tomorrow's meeting if needed about it.
