### ISSUE TITLE
[TASK] Add process proving key from circom/snarkjs encoding

### ISSUE THREAD

**Issue by drewstone** [webb-tools/zk-SaaS#21]
# Overview
We have the packed process for the arkworks proving key, we should also add one for the circom key.

**Comment by shekohex** [comment]
[Circom's ZKey can be converted to Arkworks' ProvingKey](https://github.com/arkworks-rs/circom-compat/blob/170b10fc9ed182b5f72ecf379033dda023d0bf07/src/zkey.rs#L103), so technically this already implemented.
