### ISSUE TITLE
[TASK] Audit and ensure privacy aspects are met

### ISSUE THREAD

**Issue by drewstone** [webb-tools/zk-SaaS#45]
# Overview
The foundation of the protocol is implemented but we may not have all parts of privacy handled, i.e. the `f_rand` protocol for secret sharing `r,s` of the Groth16 proof. We should audit/and task out what's remaining within this document and/or implement it if its not too challenging.

- [ ] Identify missing implementations for privacy purposes
- [ ] Update integration tests

**Comment by guruvamsi-policharla** [comment]
Writing down a list of tasks as and when I find them.

- [ ] Remove the use of `test_rng` across the repo
- [ ] Implement correlated randomness generation (for now can be done by the client)
- [ ] dFFT/diFFT should use preprocessed randomness
- [ ] dMSM should use preprocessed randomness
